# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
---
- name: 'Install Containerd'
  hosts: all
  become: true

  tasks:
    - name: containerd
      block:
        - name: load modules
          ansible.builtin.lineinfile:
            path: /etc/modules-load.d/k8s.conf
            regexp: '\b{{ item }}\b'
            line: '{{ item }}'
            create: yes
            mode: '0644'
          loop:
            - 'overlay'
            - 'br_netfilter'
          register: changed_modules

        - name: reload modules
          ansible.builtin.systemd:
            name: systemd-modules-load
            state: restarted
          when: changed_modules.changed

        - name: net.ipv4.ip_forward
          ansible.posix.sysctl:
            name: net.ipv4.ip_forward
            value: '1'
            sysctl_file: /etc/sysctl.d/99-k8s.conf
            sysctl_set: yes
            state: present
            reload: yes

        - name: net.bridge.bridge-nf-call-iptables
          ansible.posix.sysctl:
            name: net.bridge.bridge-nf-call-iptables
            value: '1'
            sysctl_file: /etc/sysctl.d/99-k8s.conf
            sysctl_set: yes
            state: present
            reload: yes

        - name: net.bridge.bridge-nf-call-ip6tables
          ansible.posix.sysctl:
            name: net.bridge.bridge-nf-call-ip6tables
            value: '1'
            sysctl_file: /etc/sysctl.d/99-k8s.conf
            sysctl_set: yes
            state: present
            reload: yes

        - name: install containerd packages
          ansible.builtin.apt:
            name: '{{ item }}'
            state: latest
          loop:
            - 'containerd'
          register: containerd_packages
            
        - name: /etc/containerd
          ansible.builtin.file:
            path: /etc/containerd
            owner: root
            group: root
            mode: '0755'
            state: directory

        - name: /etc/containerd/config.toml
          ansible.builtin.copy:
            src: ./files/etc_containerd_config.toml
            dest: /etc/containerd/config.toml
            owner: root
            group: root
            mode: '0644'
          register: containerd_config

        - name: restart containerd service
          ansible.builtin.systemd:
            name: containerd
            enabled: yes
            state: restarted
          when: containerd_packages.changed or containerd_config.changed
