# https://docs.projectcalico.org/getting-started/kubernetes/quickstart
---
- name: 'Deploy Calico to first control plane node'
  hosts: first
  become: true

  tasks:
    - name: deploy Calico to first control plane node
      block:
        - name: copy Calico custom resources
          ansible.builtin.copy:
            src: ./files/calico-custom-resources.yaml
            dest: /root/calico-custom-resources.yaml
            owner: root
            group: root
            mode: '0644'

        - name: create the Tigera Calico operator and CRDs
          ansible.builtin.shell:
            cmd: "kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml"
            chdir: "/root"
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: install Calico
          ansible.builtin.shell:
            cmd: "kubectl create -f ./calico-custom-resources.yaml"
            chdir: "/root"
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf
