---
- name: 'Clean up and provision VMs'
  hosts: all
  become: true

  tasks:
    - name: update packages
      block:
        - name: update cache
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: upgrade packages
          ansible.builtin.apt:
            name: '*'
            state: latest

        - name: install needed packages
          ansible.builtin.apt:
            name: '{{ item }}'
            state: latest
          loop:
            - 'apt-transport-https'
            - 'curl'

    - name: remove swap
      block:
        - name: swapoff
          ansible.builtin.command:
            argv:
              - swapoff
              - -a

        - name: delete swapfile
          ansible.builtin.file:
            name: '/swap.img'
            state: absent
        
        - name: clean up /etc/fstab
          ansible.builtin.lineinfile:
            path: /etc/fstab
            regexp: '\sswap\s'
            state: absent

        - name: clean up systemd swap bits
          systemd:
            name: swap.img.swap
            enabled: no
          ignore_errors: yes

    - name: fix /etc/hosts silliness
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^\s*127.0.1.1\s' 
        state: absent
