---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: "k8s.lab.cypraea.co.uk:6443"
networking:
  podSubnet: "172.20.0.0/16"
apiServer:
  timeoutForControlPlane: 5m0s
